# Machine Learning Python Tutorial
## The NumPy module - Self exercise

Development: Matan Vetzler.

In [1]:
# importing the numpy module:
import numpy as np

### NumPy - EXERCISE 1 - Element-wise addition of 2 numpy arrays

Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?



In [2]:
# given arrays:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

##### Exercise 1 - YOUR SOLUTION:

In [3]:
# YOUR SOLUTION HERE:
a + b

array([[11, 13, 15],
       [17, 19, 21]])

### NumPy - EXERCISE 2 - Multiplying a matrix (numpy array) by a scalar

Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?

In [ ]:
# given array:
a = np.array([[1,2,3],
              [4,5,6]])

##### Exercise 2 - YOUR SOLUTION:

In [4]:
# YOUR SOLUTION HERE:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

### NumPy - EXERCISE 3 - Identity Matrix

Create an identity matrix of dimension 4-by-4

##### Exercise 3 - YOUR SOLUTION:

In [34]:
# YOUR SOLUTION HERE:
identity1 = np.identity(4)
identity2 = np.eye(4)

print(identity1)
print(identity2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### NumPy - EXERCISE 4 - Horizontal Stacking of Numpy Arrays

Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays)

In [9]:
# given arrays:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

##### Exercise 4 - YOUR SOLUTION:

In [12]:
# YOUR SOLUTION HERE:
np.hstack((a1, a2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### NumPy - EXERCISE 5 - Vertically Stacking of Numpy Arrays

Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays)

In [14]:
# given arrays:
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])

##### Exercise 5 - YOUR SOLUTION:

In [15]:
# YOUR SOLUTION HERE:
np.vstack((a1, a2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [10, 11]])

### NumPy - EXERCISE 6 - Custom Sequence Generation

Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

##### Exercise 6 - YOUR SOLUTION:

In [16]:
# YOUR SOLUTION HERE:
np.arange(0, 101, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### NumPy - EXERCISE 7 - Matrix Generation with one particular value

Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

##### Exercise 7 - YOUR SOLUTION:

In [17]:
# YOUR SOLUTION HERE:
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

### NumPy - EXERCISE 8 - Array Generation of random integers within a specified range

Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)

##### Exercise 8 - YOUR SOLUTION:

In [18]:
# YOUR SOLUTION HERE:
np.random.randint(10, size=(5, 5))

array([[0, 0, 0, 3, 6],
       [6, 0, 7, 0, 9],
       [4, 1, 1, 7, 6],
       [4, 3, 5, 5, 3],
       [5, 5, 5, 4, 9]])

### NumPy - EXERCISE 9 - Matrix Multiplication

Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

In [35]:
# given arrays:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

##### Exercise 9 - YOUR SOLUTION:

In [37]:
# YOUR SOLUTION HERE:
print(np.matmul(a, b))
print(a.dot(b))

[[ 8 11]
 [13 18]]
[[ 8 11]
 [13 18]]


### NumPy - EXERCISE 10 - Matrix Transpose

Output the transpose of a matrix (as numpy array)

In [23]:
# given array:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

##### Exercise 10 - YOUR SOLUTION:

In [25]:
# YOUR SOLUTION HERE:
print(a.transpose())
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### NumPy - EXERCISE 11 - Sorting 2D array

Output the sorting of a 2D array, once on rows level and once on columns level

In [29]:
# given array:
a = np.array([[8,3,4],
              [6,5,7],
              [9,2,10]])

##### Exercise 11 - YOUR SOLUTION:

In [33]:
# YOUR SOLUTION HERE:
print(np.sort(a, axis=0))  # Rows dimension (Sort the arrays as we would look at each column as array)
print(np.sort(a, axis=1))  # Columns dimension (Sort the arrays as we would look at each row as array)

[[ 6  2  4]
 [ 8  3  7]
 [ 9  5 10]]
[[ 3  4  8]
 [ 5  6  7]
 [ 2  9 10]]
