# Machine Learning Python Tutorial
## The NumPy module - Self exercise - suggested solutions

Development: Matan Vetzler

In [2]:
# importing the numpy module:
import numpy as np

### NumPy - EXERCISE 1 - Element-wise addition of 2 numpy arrays
Given are 2 similar dimensional numpy arrays, how to get a numpy array output in which every element is an element-wise sum of the 2 numpy arrays?

In [ ]:
# given arrays:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

##### Exercise 1 - OUR SOLUTION:

In [ ]:
# OUR SUGGESTED SOLUTION:
c = a + b

print(c)

### NumPy - EXERCISE 2 - Multiplying a matrix (numpy array) by a scalar

Given a numpy array (matrix), how to get a numpy array output which is equal to the original matrix multiplied by a scalar?

In [ ]:
# given array:
a = np.array([[1,2,3],
              [4,5,6]])

##### Exercise 2 - OUR SOLUTION:

In [ ]:
# OUR SUGGESTED SOLUTION:
b = 2 * a # multiplying the numpy array a(matrix) by 2

print(b)

### NumPy - EXERCISE 3 - Identity Matrix

Create an identity matrix of dimension 4-by-4

##### Exercise 3 - OUR SOLUTION:

In [ ]:
# OUR SUGGESTED SOLUTION:
i = np.eye(4)

print(i)

### NumPy - EXERCISE 4 - Horizontal Stacking of Numpy Arrays

Stack 2 numpy arrays horizontally i.e., 2 arrays having the same 1st dimension (number of rows in 2D arrays)

In [ ]:
# given arrays:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])

##### Exercise 4 - OUR SOLUTION:

In [ ]:
# OUR SUGGESTED SOLUTION:
o = np.hstack((a1, a2))

print(o)

### NumPy - EXERCISE 5 - Vertically Stacking of Numpy Arrays

Stack 2 numpy arrays vertically i.e., 2 arrays having the same last dimension (number of columns in 2D arrays)

In [ ]:
# given arrays:
a1 = np.array([[1,2],
               [3,4],
               [5,6]])

a2 = np.array([[7,8],
               [9,10],
               [10,11]])

##### Exercise 5 - OUR SOLUTION:

In [ ]:
# OUR SUGGESTED SOLUTION:
o = np.vstack((a1, a2))

print(o)

### NumPy - EXERCISE 6 - Custom Sequence Generation

Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

##### Exercise 6 - OUR SOLUTION:

In [ ]:
# OUR SUGGESTED SOLUTION:
o = np.arange(0, 101, 2)

print(o)

### NumPy - EXERCISE 7 - Matrix Generation with one particular value

Output a matrix (numpy array) of dimension 2-by-3 with each and every value equal to 5

##### Exercise 7 - OUR SOLUTION:

In [ ]:
# OUR SUGGESTED SOLUTION:
o = np.full((2, 3), 5)

print(o)

### NumPy - EXERCISE 8 - Array Generation of random integers within a specified range

Output a 5-by-5 array of random integers between 0 (inclusive) and 10 (exclusive)

##### Exercise 8 - OUR SOLUTION:

In [ ]:
# OUR SUGGESTED SOLUTION:
o = np.random.randint(0, 10, size=(5,5))

print(o)

### NumPy - EXERCISE 9 - Matrix Multiplication

Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array)

In [3]:
# given arrays:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

##### Exercise 9 - OUR SOLUTION:

In [4]:
# OUR SUGGESTED SOLUTION:
o = np.matmul(a, b)

print(o)

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


### NumPy - EXERCISE 10 - Matrix Transpose

Output the transpose of a matrix (as numpy array)

In [ ]:
# given array:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

##### Exercise 10 - OUR SOLUTION:

In [ ]:
# OUR SUGGESTED SOLUTION:
a_transpose = a.T

print(a_transpose)

### NumPy - EXERCISE 11 - Sorting 2D array

Output the sorting of a 2D array, once on rows level and once on columns level

In [ ]:
# given array:
a = np.array([[2,4,3],
              [8,9,10],
              [5,6,7]])

##### Exercise 11 - OUR SOLUTION:

In [ ]:
# OUR SUGGESTED SOLUTION:
o_r = np.sort(a, axis=0)
print(o_r)

o_c = np.sort(a, axis=1)
print(o_c)